# FACTORIES ITEMS
command /factories_items <text> <player> <number>:
  trigger:
    if arg-1 is "oil":
      give arg-2 arg-3 of paper with custom model data 11067 named "&eOil"
    if arg-1 is "gasoline":
      give arg-2 arg-3 of paper with custom model data 11068 named "&cGasoline"
    if arg-1 is "hydrogen":
      give arg-2 arg-3 of paper with custom model data 11069 named "&bHydrogen"
    if arg-1 is "uranium":
      give arg-2 arg-3 of paper with custom model data 11070 named "&aUranium"